### ISSUE TITLE
Need help, developer needed to give a toturial

### ISSUE THREAD

**Issue by GTPManager** [Taylor-pm-pl/Clothes#45]
Basically, when i made the model, idk like wdym steve to use steve in block bench, okay basically i made it, it shows but player character is gone, i can take extra work measuring, but what do i need to do that player's skin wouldn't dissapear????

**Comment by GTPManager** [comment]
So like u didn't even solve it and closed it? Didn't even gave help? How nice ._.

**Comment by GTPManager** [comment]
I just need help, there is no such answers in google man, u are the dev, so you are the only one that can help

**Comment by taylordev47** [comment]
> So like u didn't even solve it and closed it? Didn't even gave help? How nice ._.

I can't help you because I'm just the maintainer of this plugin.
